### ISSUE TITLE
Error reading video file

### ISSUE THREAD

**Issue by sds0520** [vipoo/iRacingReplayOverlay.net#101]
Hi,
I'm using OBS for video capture, and the race capture appears to run fine (no errors in the log).  But when I select my recording (.mp4), I get "*Error reading the video file.  There is an error in XML document (0, 0)."
When I try to verify the video, I get "Unable to find target audio format."
Thoughts?
-Steve

**Comment by MerlinCooper** [comment]
Could you please provide your output seetings or your OBS-Profile.

For reference here are my output settings. 

![grafik](https://user-images.githubusercontent.com/3088879/52175144-a26f5780-279f-11e9-9b82-0d606b5f250a.png)

**Comment by MerlinCooper** [comment]
Closing due to not being able to reproduce issue w/o more information.
