### ISSUE TITLE
S12019 Update has broken Replay Director

### ISSUE THREAD

**Issue by ghost** [vipoo/iRacingReplayOverlay.net#102]
I just started using this program, but checking the forums at iRacing show several people having this issue.

When I start Replay Director, it can't find iRacing running and it won't populate the track in the camera setup.

I don't know if you're still involved with this program, I sincerely hope you are.  I was just starting to learn this when it stopped working, and wanted to recap races for my league.  Would throw a donation your way, but only if I knew you were still working on it.

Thanks for all you've done, hope to hear something!

Tim Collier

**Comment by MerlinCooper** [comment]
Root-cause is an issue in the iRacingSDK.Net library used by iRacingReplayOverlay. Try to change the return data type DataFeed/GeneratedSessionData.cs. in line 95 from long to string. That should do the trick

`public string NightMode { get; set; }`

P.S.: Bugfix to the iRacingSDK.NET was already done by Herbstein and pull request was issued. But vipoo doesn't seem to be active any longer ;-)

**Comment by MerlinCooper** [comment]
issue should be recolved after merging with sub-forkes starting with version #117
