### ISSUE TITLE
Transcode problem

### ISSUE THREAD

**Issue by mancSLO** [vipoo/iRacingReplayOverlay.net#114]
![Transcode](https://user-images.githubusercontent.com/54805675/64135341-b6d40b00-cde7-11e9-8f1c-72518ff1d3d5.jpg)
Got this message when I try to transcode video?

**Comment by MerlinCooper** [comment]
Do you have installed the plug-ins used for the Overlay? Is there a subdirectory called PlugIns. Looks like the tool can't find the plugin.

**Comment by MerlinCooper** [comment]
due to vipoo not continuing I would suggest to do the follow-up discussion in my fork of the program. 

copied / referenced your issue under 
merlincooper/iracingreplayOverlay.net#13

**Comment by MerlinCooper** [comment]
Very likely failure is caused by windows not allowing loading DLL due to no code-signing/not trusted.
