### ISSUE TITLE
Content reduction for iRacingReplayDirector (iRacingReplayOverlay)

### ISSUE THREAD

**Issue by MerlinCooper** [vipoo/iRacingReplayOverlay.net#116]
Hi all,

there was not a lot of development ongoing since Dean is no longer active in iRacing. To keep the project alive I recently joined the team and was added as co-owner for the iRacingReplayOverlay.

Since Dean started with the app back in 2016 a lot of other apps have been developed and significantly improved. Thus a view functionalities (e.g. plugins) need either to be significantly re-worked / improved to really create an incemental value or they will not be used anyway. Which requires much more effort and manpower than what I would be able to afford - and there are not a lot of other people contributing at the moment. 

Therefore I'm thinking about reducing the content of the application to the features which are still outstanding in my opinion and focuse the developemtn on the camera control and automatic (fast) creation of highlight videos. To reduce complexity I would focus on using OBS as recording software and assume that overlays are being done using third party applications (e.g. ATVO).

Before starting with significantly changing he development content and create a pure iRacingReplayDirector I wanted to see what you are thinking about that approach. 

Please provide feedback to this idea.

**Comment by mrzoops** [comment]
Love the idea but would like to continue using Nvidia capture as well. Are you still working on this at all? Such a great tool for it to not be updated.

**Comment by MerlinCooper** [comment]
Yes still working on it from time to time - most likely I will be able to spend some time over XMas. Work is mostly done on my fork (makes it just easier).

https://github.com/MerlinCooper/iRacingReplayDirector
