### ISSUE TITLE
The events box should disappear when nothing happens

### ISSUE THREAD

**Issue by PascalHigelin** [vipoo/iRacingReplayOverlay.net#12]

**Comment by LGRDDOG** [comment]
I don't know about the fade if nothing happens after a while, as most of my events have too much going on to fit in the 3 lines that are available ;)

However I do like the idea, but would like to add that it should be user configurable, as well as possibly the total amount of lines displayed.

Perhaps something along the lines of what some stream chat overlays do for twitch, where it has a box where a maximum of X lines can show up, but each "event" or line, has it's own individual timeout where that line will fade off, unless it's bumped past the maximum lines.
