### ISSUE TITLE
Add configuration allow incidents to be shown on first sectors

### ISSUE THREAD

**Issue by vipoo** [vipoo/iRacingReplayOverlay.net#20]
At moment, first lap always followers leader (1st qualifier) - allow switch to show incidents

**Comment by LGRDDOG** [comment]
Was going to suggest this, but I'm glad I peeked in here first.  Especially with many races now having large grids, and sometimes even full-lap pace laps, it would be great if you had the option to *NOT* force focus on the leader, as very often the leader during pace lap, as well as going green, is where the action is....unfortunately...not :)
