### ISSUE TITLE
Keep Awake

### ISSUE THREAD

**Issue by Komoman** [vipoo/iRacingReplayOverlay.net#73]
Windows 10 power management shuts down the computer even if the CPU is being heavily utilized by the app. Possible to add Keep Awake?

https://msdn.microsoft.com/en-us/library/aa373208(VS.85).aspx?tduid=(526b0ccca9782105839e816b40135ed0)(256380)(2459594)(TnL5HPStwNw-zjXVcMDt2qhG7EOzbZ5Opw)()

**Comment by vipoo** [comment]
Changes for this feature have been commited.  87e942975fdcfbb5a2dbc404805267e60673d60b
Released to the test stream

**Comment by Komoman** [comment]
Awesome, will test with a Daytona 24 last hour highlight, thanks!
