### ISSUE TITLE
Full transcoding not working anymore

### ISSUE THREAD

**Issue by SpirouHyluan** [vipoo/iRacingReplayOverlay.net#75]
Hi Dean,

I tried some times to transcode a full race and it is not working anymore. Highlights video is created, full race too but is empty or corrupted. I am using prerelease version with last standard overlay.

Also, it might be interesting to create only the full race sometimes.

Thanks for all your work.

**Comment by vipoo** [comment]
Not sure if I have reproduced this issue.

Please confirm if your issue still persists with pre-release version: 1.0.3.34

Cheers
Dean

**Comment by vipoo** [comment]
I believe this issue has been correct as per the latest versions.

Please advise if otherwise.
