### ISSUE TITLE
Enhancement : analyse of overtakes and limitation of the video capture

### ISSUE THREAD

**Issue by SpirouHyluan** [vipoo/iRacingReplayOverlay.net#77]
Dean,

I know you worked on this and i think it is a huge upgrade to the soft !

Also, you might consider something about this. You sure know IRTVO, the famous overlay on Iracing. It is not working properly on replays. But I'm sure that wtih your SDK it could be working on replays.

Then, if you manage to capture only the higlights and use a proper IRTVO on it, you could avoid the transcoding part. Which could be awesome because of the time gained , the maintenance gained and the capability for the user to choose exactly the video and sound quality he want to have.

Cheers for all your hard work !

Josua

**Comment by vipoo** [comment]
At this stage, I dont wish to attempt to integrate to IRTVO - I appreciate what you are saying, but I feel it would not be a trivial integration process.  Plus I feel it would make diagnosing issue more complicated - potentially issues across 2 applications.

I could be wrong... but i think i would prefer to leave that for someone else to do.

In terms of the overlay quality - I appreciate this is a 'poorer' part of the application.  To address this, I am building a overlay plugin architecture for the application, to allow users to select an overlay driver.

And other coders can build overlays.

I have another individual, who is offering some design services, to help improve the quality of the overlay.

Dean.
