### ISSUE TITLE
Replay director fails to make any highlight or full-race replay if there is no qualify portion within the replay file

### ISSUE THREAD

**Issue by LGRDDOG** [vipoo/iRacingReplayOverlay.net#82]
I originally thought that this issue was dealt with, however I'm still encountering this.  It may be that I just started saving my .rpy as a full session, and not cropping it anymore that resolved it, however sometimes I get replays from other members that would like my "Magic" for a highlight reel, and they occasionally crop the replay from sometime during the grid-start, to post race.

I am having this issue with this particular file:
Dropbox link: [(https://www.dropbox.com/s/jcs393e5mjb97yy/BES%40Sonoma%28Partial%29.rpy?dl=0)](url)

If you need some log files, I can attempt to run it again for a 3rd time as I forgot to keep the error info, although it should be in whatever reports automatically get sent to you from your program ;)

Just in case Dropbox is being stupid, here's the same file via MEGA instead [https://mega.nz/#!AtYTTboa!Qt7Pc1-mdct-h88c1q7az8xM9rfZowKNN4OWV5G8t9Y](url)

**Comment by vipoo** [comment]
Sorry - but the links are returning 404 for me.

As there are lots of people who use the app, for me to see your logs I need your TrackingId and the time you attempted to convert.

**Comment by LGRDDOG** [comment]
Strange.  If I click on the links in here, it comes up as a 404, however if I copy/paste them into a browser, they come up properly.  Not too sure what's up with that.

As for the TrackingID and time, how would I go about finding that out?  The time would be pretty self explanitory, however I don't know where to find the TrackingID.

**Comment by vipoo** [comment]
Thanks - I did as you suggest, and pasted link - and am able to get file -
need to download it at home (on work machine at moment)

TrackingId can be found by clicking the About button.

Cheers
Dean

**Comment by LGRDDOG** [comment]
I haven't encountered any issues with replays that do not have a qualify portion anymore, so I believe this one can be closed now.  Thank you Dean ;)
