### ISSUE TITLE
Option to have highlight made with NO overlays

### ISSUE THREAD

**Issue by LGRDDOG** [vipoo/iRacingReplayOverlay.net#83]
While your standard overlays are more than acceptable, I know that I would like to test out some other overlays with your program's direction for the actual clips to be taken.

If there was an option to create the highlight reel and/or full-race replay with NO overlay, then users would be able to have their overlay program (ie: IRTVO or APTO etc) running and being captured during the initial recording phaze, then have your program simply do the work of cropping the proper clips out and making the video, without having to insert the overlays at the same time, potentially speeding up the process as well.

**Comment by MerlinCooper** [comment]
Starting with #117 you can now create / transcode a highlight video without an overlay. 

Just make sure that in the options dialog NO PlugIn is selected. 

![grafik](https://user-images.githubusercontent.com/3088879/81972851-86559980-9623-11ea-969e-d587a7795089.png)
