### ISSUE TITLE
Need guidance on recording software

### ISSUE THREAD

**Issue by daones** [vipoo/iRacingReplayOverlay.net#84]
So this looks like a great tool and eager to get it working as it will save me a lot of time editing. The issue is so far I have not found a tool that works with this overlay. I tried Plays.tv recording software and that does not work... it says something like "The byte stream type of the given URL is unsupported."

So I tried Open Broadcast Software, made the settings updated to work with this. But this then says "File already in use" when trying to verify the video capture.

Also I tried Xsplit Broadcaster, where I guess the video worked but then it says "Unable to find target audio format". In Xsplit they are using AAC LC HQ and Speex so are none of those supported?

So to save me the time of trying every software out there maybe some help with changing settings in the above tools to get it working or suggest a new one. I cant use Nvidia as I have an AMD card.

**Comment by vipoo** [comment]
I have used bandicam with success.

No matter the tool, make sure you choose H264 (mpeg) encoding for video,
and audio as PCM or unencoded; this should work.

there is a PDF in the iRacing forum, that a user has detailed on setting up
OBS software.

There is a patch in the works, to better support other video formats -
sorry no ETA on when it will be released.

Also it may be worth posting your challenge on the iRacing forum - as lots
of users there have got OBS working sucessfully.


Cheers
Dean

**Comment by LGRDDOG** [comment]
I haven't attempted using OBS for Replay Director as I have it specifically set up for my streaming to twitch, however the settings should be very similar.  I may attempt a short replay with it to see if I can get it working, and if it does, I can screenshot my settings for you.

Unfortunate that you do not have a NVidia Card, as it's, by far, the easiest implementation I've used, and rather seamless to use with Replay Director imo.  That being said, previous to switching to NVidia's Shadowplay, I used Bandicam with rather good success.  Took a little bit to realize that the defaults aren't what are required by Replay Director to get the best quality, however it works like a charm for well over a year or more, and was still working great the last time I tried it.

Unfortunate part is it IS a paid program :( but the cost wasn't too much imo, and well worth it for what it can do.

I then also take the completed replays/highlights from Replay Director, and run them through another program (free) called "Handbrake" which keeps the quality (both sound and visual) the same, however compresses it drastically, ending up with most of the time a completed file to upload to YouTube that's half the size of what Replay Director spits out, and about 1/10th the size of the original replay recording that is initially captured.

Here's the links for both if you're interested:
[https://www.bandicam.com/](url)
[https://handbrake.fr/](url)

**Comment by MerlinCooper** [comment]
Not sure whether you have been able to get this running. 

Just wanted you to know that in future versions the development of the tool will focus on usage to together with OBS as video capturing software. 

OBS is free and does support streaming to twitch as well - furthermore it's recommendid to use the iRacingReplayDirector only when recording videos to your hard drive and not streaming.
