### ISSUE TITLE
Opening replay in sim will not trigger the "Begin Capture" capability on certain events

### ISSUE THREAD

**Issue by LGRDDOG** [vipoo/iRacingReplayOverlay.net#93]
I'm really not sure why this is, however, I've been getting this off and on since I started using the program.  I normally chalked it up to a messed up replay on my end, as it normally happened when I had some other unrelated PC issue around the same time as when I participated in the event, however, recently I've been discovering that there are some events that will not trigger the "Begin Capture" button to start the program, regardless of what split/who captured the replay.

Case in point, the 19:00 GMT Saturday Blancpain Endurance Series race that we had earlier today.

3 splits, with myself, being in the bottom and saved the entire 3-hour replay.  Replay works perfectly with anything except Replay Director.  The version of iRRD does not matter I believe as I tried a good half dozen different ones and still had zero luck.

Just to rule out something on my end, I had another iRacing member send me a copy of the full race, however, a different split.  This time being Top Split.  Exact same issue as the replay that I saved.  Something about this particular event is not triggering the "Begin Capture" button in iRRD.

I even attempted to load a short clip, simply to see if it would trigger with no luck.

Any other replay, as long as it is not from this particular event, works perfectly, so it seems that there is sometimes, something with an event that prevents iRRD from properly triggering.  Everything in the log file looks normal from what I can see, and loading another event replay gives me no differing log information.

I'm hoping you may be able to discover what the issue is and possibly figure out a workaround, however, I am also going to be contacting iRacing Support on Monday and seeing if I can get some further insight from their end, as it's not just your program that's having this issue with some events.  All of my normal programs that I use were not able to gather information from this event such as iRacing Browser Apps (for streaming overlays with relative, standings, track map etc) and even DashmeterPro was having issues.

Here is the replay from the event that will not trigger, as well as a short clip from the event as a smaller download if you wanted to test for yourself.

Full Race (compressed with 7zip) = [https://mega.nz/#!V1By3TCR!e6Ks73Nzbb45xiZf1NPjEZ4Kl9X229AenF-e7gz2gi8](url)
Short Clip = [https://mega.nz/#!t1RmRR5K!t8Yt9RI7nnSKxjVzYpJG5u20-L75Cm5Uu74cU8hpTEI](url)

For the sake of comparison, here is the event replay of the absolute previous event on the schedule, that worked with no issues.

Full Race (Compressed with 7zip) = [https://mega.nz/#!t5gmVChA!tzn0oUHfwA8bItSSKrx9m6IoYwWl6LFRJhc2UCt2Nf8](url)

If it is of any help, my tracking ID is:  4062868663483498496

**Comment by dnetherton** [comment]
Interesting....

I will try and do an investigation asap for ya.  (Just not quite sure when that might be - it may end up being the weekend)

Dean

**Comment by LGRDDOG** [comment]
Thank you, Dean.  like I mentioned above, I've noticed this before, but attributed it to other causes.  Since I've started focusing my YouTube Channel exclusively on the iRacing Blancpain Series, with exact series event times, and a regular video release schedule, I'm actually starting to get other people helping me obtain full replay files from the weekend Endurance Series splits that I'm not qualified to enter (Top Splits)

Unfortunately, this issue is starting to crop up a little more often now that I'm participating in larger official events now instead of small league events.

I have a sneaky suspicion that it may have something to do with iRacings preventative measures against DDoS attacks, as looking back, most of the time when I get a replay that does this, there has been a larger number of clients dropping from the server to throughput issues, as well as myself noticing more quality spikes.

**Comment by MerlinCooper** [comment]
There was a failure mode where iRacingReplayDirector (formerly iRacingsReplayOverlay) did not recognize that iRacing was running due to a failure in the YamlDotNet nuget Package. 

When using YamlDotNet V5.3.1. this failure mode is fixed - but it's going to be re-introduced when upgrading to V8.1.1. => continue using YamlDotNet V5.3.1. and do NOT upgrade. 

Not sure whether you are still using/following the iRacingReplayDirector Development but feel free to test-out #117 (Version 1.1.0.0).
