### ISSUE TITLE
Transcoding creates unwatchable video file(s)

### ISSUE THREAD

**Issue by Grimzentide** [vipoo/iRacingReplayOverlay.net#95]
v1.03.58 and v1.03.60

![vlcsnap-error462](https://cloud.githubusercontent.com/assets/13880327/21077134/50e955b6-bf94-11e6-8225-cc332ac30754.png)

Verify video works and previous transcoding also worked.  The source video file is recorded via OBS correctly and is watchable.

**Comment by jboeddeker** [comment]
I have a similar result, recorded via bandicam/AMD APP

**Comment by jboeddeker** [comment]
It's just the full transcoding, which goes wrong, the verify video stuff produces a good video. I'm trying some older versions.
