### ISSUE TITLE
[RFE] Highlight-only capture (not transcode)

### ISSUE THREAD

**Issue by thoraxe** [vipoo/iRacingReplayOverlay.net#97]
Would it be possible to add an option to only create a highlight video, as opposed to full race + highlights? Does Director need to "watch" the entire race to be able to find the incidents/passes/etc?

**Comment by thoraxe** [comment]
I am updating this RFE because I've learned a little more about the program.

Currently the program will generate a full-length capture of the race. It then can transcode/encode, and this is when the highlight video is created. 

I actually want to create a highlight-only capture. Open Broadcaster's output file is already exactly the quality that I want, and it already includes the overlays that I want.

The other option would be to disable overlays all together on transcode/encode.

**Comment by thoraxe** [comment]
This is related to: https://github.com/vipoo/iRacingReplayOverlay.net/issues/83

**Comment by MerlinCooper** [comment]
Option to create highlight video w/o an overlay is already implemented #83. 

Possibilities to speed up creation of a highlight video w/o playing out the video in full length in realtime are in development in this branch. 

https://github.com/MerlinCooper/iRacingReplayDirector/tree/Fast_Video_Recording_With_OBS
